import assert from 'node:assert/strict';
import { RequestRegistry } from '../handoff/PARALLEL_MODEL_ADAPTER_20260913/src/dedupe.mjs';
import { CameraController } from '../handoff/PARALLEL_CAMERA_20260913/src/camera-controller.mjs';
import { createModelProviderAdapter } from '../../jianwei-v3/site/lib/v5-preview/remote-service.ts';
// Read-only module probes; synthetic objects only. Assertions reproduce defects, not acceptance.
const registry = new RequestRegistry({maxEntries:2});
registry.track('a','hash-a',new Promise(()=>{}));
registry.track('b','hash-b',new Promise(()=>{}));
registry.track('c','hash-c',new Promise(()=>{}));
assert.equal(registry.lookup('a','hash-a').kind,'register');
console.log('A: capacity eviction forgets an in-flight request, allowing duplicate registration');
let resolveStream; let stops=0;
const track={readyState:'live',stop(){stops++;this.readyState='ended';}};
const camera=new CameraController({isSecureContext:true,mediaDevices:{getUserMedia:()=>new Promise(r=>resolveStream=r)},ImageCapture:class {takePhoto(){return Promise.resolve(new Blob(['synthetic'],{type:'image/png'}));}},decodeImageMetadata:async()=>null,createThumbnail:async()=>null,createObjectURL:()=>null});
camera.openFromUserGesture(); resolveStream({getVideoTracks:()=>[track],getTracks:()=>[track]});
await new Promise(r=>setImmediate(r)); camera.capture(); await new Promise(r=>setImmediate(r));
assert.equal(camera.state,'preview'); assert.equal(stops,0);
console.log('B: successful capture leaves camera track live until explicit close/dispose'); camera.dispose();
let resolveModel; const req={requestId:'same',sessionId:'s',annotationId:'a',sessionStatus:'live',evidenceRef:{fixtureId:'fixture-inspection',sha256:'x',version:1},domainRoles:['credit'],purpose:'follow_up_generation'};
const adapter=createModelProviderAdapter({timeoutMs:20,handler:()=>new Promise(r=>resolveModel=r)});
const pending=adapter.generateFollowUps(req); req.sessionStatus='paused'; resolveModel({followUps:[{domainRole:'credit',text:'合成问题'}]});
const result=await pending; assert.equal(result.status,'ok');
const replay=await adapter.generateFollowUps({...req,annotationId:'different'}); assert.equal(replay.status,'ok');
console.log('MAIN: pause during await still returns ok; same ID changed payload returns cached ok');
