import type { FlowWorkspace } from './flow-workspaces.ts';

export const POLICY_WORKSPACES = {
  'policy-material': {
    id: 'policy-material',
    type: 'policy-material-workspace',
    headline: '材料解析：一次接入，四路共享同一证据版本',
    objective: '将合成材料完成 OCR、分类和字段映射，形成唯一 Canonical Evidence/Event，不复制四份事实。',
    visualization: {
      type: 'OCR分类字段映射与共享信息分发图',
      title: '材料解析与四板块共享分发',
      description: '同一份脱敏设备说明生成一个证据事件，由政策、信审、商务、资产四条候选处理链消费。',
      items: [
        { id: 'material-ocr', label: 'OCR', value: '36 个候选字段', status: '候选已抽取' },
        { id: 'material-classify', label: '分类', value: '设备/合同/经营', status: '已分类' },
        { id: 'material-map', label: '字段映射', value: '29/36', status: '7 项待核' },
        { id: 'material-share', label: '共享分发', value: '4 路', status: '同一 Context Version' },
      ],
    },
    matrix: {
      title: '材料分类、字段、可信度、原始定位与上下文版本矩阵',
      columns: [
        { key: 'material', label: '材料' }, { key: 'classification', label: '分类' },
        { key: 'section', label: '栏目' }, { key: 'field', label: '字段' },
        { key: 'confidence', label: '可信度' }, { key: 'location', label: '原始定位' },
        { key: 'contextVersion', label: 'Context Version' },
      ],
      rows: [
        { id: 'material-row-001', cells: { material: '设备技术说明（脱敏）', classification: '租赁物', section: '设备参数', field: '额定精度 0.005mm', confidence: '94% 候选', location: '第3页 / 参数表第4行', contextVersion: '读取 Projection 当前版本' } },
        { id: 'material-row-002', cells: { material: '承租人经营摘要（合成）', classification: '经营材料', section: '产能', field: '五轴单元连续作业', confidence: '81% 候选', location: '第2页 / 生产说明', contextVersion: '读取 Projection 当前版本' } },
      ],
    },
    graph: {
      nodes: [
        { id: 'material-source', label: '唯一合成材料', kind: 'evidence', active: true },
        { id: 'material-parser', label: '候选 OCR/分类 Agent', kind: 'agent', active: true },
        { id: 'material-event', label: 'Canonical Evidence/Event', kind: 'context', active: true },
        { id: 'material-gate', label: '材料解析 Gate（周宁）', kind: 'gate', active: true },
        { id: 'material-target', label: '四路候选处理', kind: 'target', active: false },
      ],
      edges: [
        { id: 'policy-material-e1', source: 'material-source', target: 'material-parser', label: '一次接入' },
        { id: 'policy-material-e2', source: 'material-parser', target: 'material-event', label: '生成唯一事件' },
        { id: 'policy-material-e3', source: 'material-event', target: 'material-gate', label: '等待具名确认' },
        { id: 'policy-material-e4', source: 'material-event', target: 'material-target', label: '共享同一版本' },
      ],
    },
    indicators: [
      { label: '接入次数', value: '1 次', note: '没有四份重复上传' },
      { label: '共享消费者', value: '4 路', note: '同一 Context Version' },
      { label: '候选字段', value: '36 个', note: '7 项仍待人工核验' },
    ],
    evidenceGaps: ['设备出厂检验页缺失。', '经营摘要没有原始回执。'],
    nextActions: ['复核材料分类与栏目。', '确认原始定位可回链。', '接受后向四条候选处理链广播版本。'],
    currentSituation: '唯一材料事件已经形成候选，四个板块将读取同一 Context Version。',
    whyMe: '周宁负责材料接入边界；模型只做候选解析，authority=none。',
    aiCompleted: ['已完成候选 OCR 与分类。', '已生成候选字段映射和四路分发清单。'],
    primaryHumanAction: { action: '确认材料分类、原始定位和共享范围。', owner: '材料解析·周宁', evidenceGap: '出厂检验页与经营原始回执。', humanGate: '材料解析 Gate' },
    nextHandoff: { target: 'policy-rules', receiver: '规则核验·徐朔', contextPacket: ['事项编号', 'Context Version', 'Evidence Event ID', '字段映射', '证据缺口'] },
    successReceiptCondition: '周宁提交后 Receipt 记录唯一 Evidence Event、Context Version 与四个消费者。',
  },
  'policy-rules': {
    id: 'policy-rules',
    type: 'policy-rules-workspace',
    headline: '规则核验：准入条款命中与例外等待人工裁定',
    objective: '把共享字段与系统规则逐项核对，暴露客户、主体、设备和租赁结构的缺口与例外。',
    visualization: {
      type: '系统规则适用与例外图',
      title: '准入规则命中、缺口与例外关系',
      description: '规则匹配是候选解释；政策人员裁定例外，模型没有准入权。',
      items: [
        { id: 'rules-hit', label: '明确命中', value: '14 条', status: '候选' },
        { id: 'rules-gap', label: '证据缺口', value: '3 条', status: '待补证' },
        { id: 'rules-exception', label: '例外', value: '2 条', status: '待裁定' },
        { id: 'rules-version', label: '规则版本', value: 'POLICY-v2.4', status: '受控引用' },
      ],
    },
    matrix: {
      title: '规则 × 客户、主体、设备、租赁结构命中矩阵',
      columns: [
        { key: 'rule', label: '规则' }, { key: 'customer', label: '客户/主体' },
        { key: 'equipment', label: '设备' }, { key: 'structure', label: '租赁结构' },
        { key: 'hit', label: '命中' }, { key: 'gap', label: '缺口' }, { key: 'exception', label: '例外' },
      ],
      rows: [
        { id: 'rules-row-001', cells: { rule: '制造业设备直租准入', customer: '精密零件制造主体', equipment: '五轴数控机床', structure: '直租', hit: '候选命中', gap: '出厂检验页', exception: '无' } },
        { id: 'rules-row-002', cells: { rule: '单一主体集中度上限', customer: '民营制造企业', equipment: '通用生产设备', structure: '直租', hit: '待量化', gap: '组合余额口径', exception: '可能超过 15%' } },
      ],
    },
    graph: {
      nodes: [
        { id: 'rules-context', label: '共享字段版本', kind: 'context', active: true },
        { id: 'rules-engine', label: '候选规则核验 Agent', kind: 'agent', active: true },
        { id: 'rules-result', label: '命中与例外清单', kind: 'rule', active: true },
        { id: 'rules-gate', label: '规则核验 Gate（徐朔）', kind: 'gate', active: true },
        { id: 'rules-target', label: '量化评估', kind: 'target', active: false },
      ],
      edges: [
        { id: 'policy-rules-e1', source: 'rules-context', target: 'rules-engine', label: '输入共享字段' },
        { id: 'policy-rules-e2', source: 'rules-engine', target: 'rules-result', label: '输出候选命中' },
        { id: 'policy-rules-e3', source: 'rules-result', target: 'rules-gate', label: '例外待裁定' },
        { id: 'policy-rules-e4', source: 'rules-gate', target: 'rules-target', label: '裁定后接续' },
      ],
    },
    indicators: [
      { label: '规则条目', value: '19 条', note: '14 命中 / 3 缺口 / 2 例外' },
      { label: '受控版本', value: 'v2.4', note: '不等于已批准项目' },
      { label: '模型权限', value: 'none', note: '徐朔裁定规则例外' },
    ],
    evidenceGaps: ['组合余额口径没有回执。', '出厂检验页未接入。'],
    nextActions: ['核对规则版本。', '裁定两条例外。', '将确认规则交给量化评估。'],
    currentSituation: '多数规则候选命中，但集中度例外和检验页缺口未闭合。',
    whyMe: '徐朔维护规则适用口径；模型只提示候选命中，authority=none。',
    aiCompleted: ['已完成候选规则匹配。', '已生成候选例外与缺口清单。'],
    primaryHumanAction: { action: '裁定两条例外并确认规则适用范围。', owner: '规则核验·徐朔', evidenceGap: '组合余额与出厂检验页。', humanGate: '规则核验 Gate' },
    nextHandoff: { target: 'policy-quant', receiver: '量化评估·沈知行', contextPacket: ['Context Version', '规则版本', '命中规则', '例外裁定', '缺口清单'] },
    successReceiptCondition: '徐朔提交后 Receipt 列出适用规则、例外理由和缺口影响。',
  },
  'policy-quant': {
    id: 'policy-quant',
    type: 'policy-quant-workspace',
    headline: '量化评估：六维贡献已归一，异常解释待复核',
    objective: '将共享事实归一化为六维候选画像，展示权重、贡献和异常解释，不输出审批概率。',
    visualization: {
      type: '归一化与六维画像图',
      title: '六维候选画像与贡献分解',
      description: '归一值和贡献度仅用于政策候选评估，不是批准概率。',
      items: [
        { id: 'quant-operation', label: '经营', value: '0.72', status: '候选归一值' },
        { id: 'quant-cash', label: '现金流', value: '0.58', status: '波动待核' },
        { id: 'quant-equipment', label: '设备', value: '0.81', status: '检验页缺失' },
        { id: 'quant-structure', label: '结构', value: '0.66', status: '例外影响' },
      ],
    },
    matrix: {
      title: '维度、原始值、归一值、权重、贡献度与异常矩阵',
      columns: [
        { key: 'dimension', label: '维度' }, { key: 'raw', label: '原始值' },
        { key: 'normalized', label: '归一值' }, { key: 'weight', label: '权重' },
        { key: 'contribution', label: '贡献度' }, { key: 'evidence', label: '证据' }, { key: 'anomaly', label: '异常解释' },
      ],
      rows: [
        { id: 'quant-row-001', cells: { dimension: '经营稳定性', raw: '产线连续作业候选', normalized: '0.72', weight: '24%', contribution: '17.3', evidence: '经营摘要与现场事实', anomaly: '缺原始经营回执' } },
        { id: 'quant-row-002', cells: { dimension: '租赁物能力', raw: '精度 0.005mm', normalized: '0.81', weight: '20%', contribution: '16.2', evidence: '设备说明第3页', anomaly: '出厂检验页缺失' } },
      ],
    },
    graph: {
      nodes: [
        { id: 'quant-rules', label: '确认规则与共享事实', kind: 'rule', active: true },
        { id: 'quant-agent', label: '候选归一计算 Agent', kind: 'agent', active: true },
        { id: 'quant-profile', label: '六维贡献画像', kind: 'metric', active: true },
        { id: 'quant-gate', label: '量化评估 Gate（沈知行）', kind: 'gate', active: true },
        { id: 'quant-target', label: '智能预审', kind: 'target', active: false },
      ],
      edges: [
        { id: 'policy-quant-e1', source: 'quant-rules', target: 'quant-agent', label: '输入规则与事实' },
        { id: 'policy-quant-e2', source: 'quant-agent', target: 'quant-profile', label: '归一与贡献分解' },
        { id: 'policy-quant-e3', source: 'quant-profile', target: 'quant-gate', label: '异常待复核' },
        { id: 'policy-quant-e4', source: 'quant-gate', target: 'quant-target', label: '确认后预审' },
      ],
    },
    indicators: [
      { label: '画像维度', value: '6 维', note: '全部是候选归一值' },
      { label: '异常解释', value: '2 项', note: '现金流与检验页' },
      { label: '审批概率', value: '不提供', note: '候选准备与权威分离' },
    ],
    evidenceGaps: ['现金流波动口径未确认。', '设备检验页缺失。'],
    nextActions: ['确认六维权重。', '解释两项异常。', '冻结候选画像版本。'],
    currentSituation: '六维候选画像已生成，两个异常维度仍需政策量化人员复核。',
    whyMe: '沈知行负责量化口径；模型仅计算候选贡献，authority=none。',
    aiCompleted: ['已完成候选归一化。', '已生成候选贡献分解和异常解释。'],
    primaryHumanAction: { action: '确认权重、异常解释和候选画像版本。', owner: '量化评估·沈知行', evidenceGap: '现金流口径与设备检验页。', humanGate: '量化评估 Gate' },
    nextHandoff: { target: 'policy-prereview', receiver: '智能预审·罗砚', contextPacket: ['Context Version', '六维画像', '规则例外', '异常解释', '量化 Gate Receipt'] },
    successReceiptCondition: '沈知行提交后 Receipt 固定权重、贡献和异常解释版本。',
  },
  'policy-prereview': {
    id: 'policy-prereview',
    type: 'policy-prereview-workspace',
    headline: '智能预审：候选结论依赖两项人工问题',
    objective: '汇总支持与反对证据，明确 Human Gate 依赖；候选预审不能替代政策或信审决定。',
    visualization: {
      type: '候选结论与HumanGate依赖图',
      title: '候选预审结论与人工问题依赖',
      description: '候选建议、反对证据与 Gate 问题并列呈现，不生成正式通过状态。',
      items: [
        { id: 'prereview-result', label: '候选结论', value: '有条件进入信审', status: '非正式' },
        { id: 'prereview-support', label: '支持证据', value: '4 项', status: '可回链' },
        { id: 'prereview-oppose', label: '反对证据', value: '2 项', status: '待裁定' },
        { id: 'prereview-question', label: '人工问题', value: '2 个', status: '等待 Gate' },
      ],
    },
    matrix: {
      title: '判断项、候选结论、支持反对证据与人工问题矩阵',
      columns: [
        { key: 'judgment', label: '判断项' }, { key: 'candidate', label: '候选结论' },
        { key: 'support', label: '支持证据' }, { key: 'oppose', label: '反对证据' },
        { key: 'confidence', label: '置信提示' }, { key: 'humanQuestion', label: '待人工问题' }, { key: 'impact', label: '影响' },
      ],
      rows: [
        { id: 'prereview-row-001', cells: { judgment: '政策准入', candidate: '候选有条件进入', support: '制造业直租规则命中', oppose: '集中度例外待定', confidence: '中等提示', humanQuestion: '是否接受集中度例外？', impact: '影响信审前置条件' } },
        { id: 'prereview-row-002', cells: { judgment: '设备适格', candidate: '候选暂缓', support: '设备参数可回链', oppose: '检验页缺失', confidence: '低提示', humanQuestion: '缺页是否允许补证后接续？', impact: '影响事实核验范围' } },
      ],
    },
    graph: {
      nodes: [
        { id: 'prereview-profile', label: '六维候选画像', kind: 'metric', active: true },
        { id: 'prereview-agent', label: '候选预审 Agent', kind: 'agent', active: true },
        { id: 'prereview-result-node', label: '支持/反对证据', kind: 'judgment', active: true },
        { id: 'prereview-gate', label: '智能预审 Gate（罗砚）', kind: 'gate', active: true },
        { id: 'prereview-target', label: '智能更新', kind: 'target', active: false },
      ],
      edges: [
        { id: 'policy-prereview-e1', source: 'prereview-profile', target: 'prereview-agent', label: '输入画像与规则' },
        { id: 'policy-prereview-e2', source: 'prereview-agent', target: 'prereview-result-node', label: '生成候选判断' },
        { id: 'policy-prereview-e3', source: 'prereview-result-node', target: 'prereview-gate', label: '人工问题待决' },
        { id: 'policy-prereview-e4', source: 'prereview-gate', target: 'prereview-target', label: '决定后更新' },
      ],
    },
    indicators: [
      { label: '候选判断', value: '2 项', note: '一项有条件 / 一项暂缓' },
      { label: '人工问题', value: '2 个', note: '必须具名回答' },
      { label: '模型权限', value: 'none', note: '不能正式预审通过' },
    ],
    evidenceGaps: ['集中度例外未裁定。', '出厂检验页未补齐。'],
    nextActions: ['查看支持与反对证据。', '回答两个具名问题。', '记录预审 Gate Receipt。'],
    currentSituation: '候选预审建议有条件接续，但两项人工问题未回答。',
    whyMe: '罗砚是预审 Gate Owner；模型只生成候选判断，authority=none。',
    aiCompleted: ['已汇总候选支持与反对证据。', '已生成候选预审问题。'],
    primaryHumanAction: { action: '回答两项问题并决定接续、补证或阻断。', owner: '智能预审·罗砚', evidenceGap: '集中度裁定与出厂检验页。', humanGate: '智能预审 Gate' },
    nextHandoff: { target: 'policy-update', receiver: '智能更新·方遥', contextPacket: ['Context Version', '候选预审结论', '支持/反对证据', '人工问题答案', 'Gate Receipt'] },
    successReceiptCondition: '罗砚提交后 Receipt 记录人工答案、结论和信审前置条件。',
  },
  'policy-update': {
    id: 'policy-update',
    type: 'policy-update-workspace',
    headline: '智能更新：回流事件准备生成下一 Context Version',
    objective: '把规则、信审、商务和资产回流追加为新版本，保留 V1/V2/V3 变化、Receipt 与回退点。',
    visualization: {
      type: '版本反馈与四板块回流图',
      title: '四板块反馈、版本变化与回退路径',
      description: '更新只追加 Event 和 Context Version；旧 Evidence、Receipt 与版本不可覆盖。',
      items: [
        { id: 'update-v1', label: 'V1', value: '材料初始接入', status: '保留' },
        { id: 'update-v2', label: 'V2', value: '规则例外反馈', status: '当前候选' },
        { id: 'update-v3', label: 'V3', value: '待 Gate 后生成', status: '未创建' },
        { id: 'update-feedback', label: '四路回流', value: '政策/信审/商务/资产', status: '共享' },
      ],
    },
    matrix: {
      title: '版本变化、触发事件、影响、回执、回退点与下一版本矩阵',
      columns: [
        { key: 'version', label: '版本' }, { key: 'change', label: '变化' },
        { key: 'trigger', label: '触发事件' }, { key: 'impact', label: '影响范围' },
        { key: 'receipt', label: '回执' }, { key: 'rollback', label: '回退点' }, { key: 'next', label: '下一 Context Version' },
      ],
      rows: [
        { id: 'update-row-001', cells: { version: 'V1 → V2', change: '新增集中度例外', trigger: '规则核验反馈事件', impact: '政策与信审候选链', receipt: '规则 Gate 待记录', rollback: 'V1 Evidence 保留', next: 'Gate 后生成' } },
        { id: 'update-row-002', cells: { version: 'V2 → V3', change: '补入设备检验页', trigger: '新 Evidence 接入', impact: '四板块同一版本', receipt: 'Evidence 接受回执待生成', rollback: 'V2 可复读', next: 'CTX 序列 +1' } },
      ],
    },
    graph: {
      nodes: [
        { id: 'update-feedback-node', label: '四板块回流事件', kind: 'context', active: true },
        { id: 'update-agent', label: '候选影响分析 Agent', kind: 'agent', active: true },
        { id: 'update-lineage', label: 'V1/V2/V3 版本血缘', kind: 'version', active: true },
        { id: 'update-gate', label: '智能更新 Gate（方遥）', kind: 'gate', active: true },
        { id: 'update-target', label: '信审模型解析', kind: 'target', active: false },
      ],
      edges: [
        { id: 'policy-update-e1', source: 'update-feedback-node', target: 'update-agent', label: '追加回流事件' },
        { id: 'policy-update-e2', source: 'update-agent', target: 'update-lineage', label: '生成候选差异' },
        { id: 'policy-update-e3', source: 'update-lineage', target: 'update-gate', label: '等待版本确认' },
        { id: 'policy-update-e4', source: 'update-gate', target: 'update-target', label: '新版本接续信审' },
      ],
    },
    indicators: [
      { label: '保留版本', value: '2 个', note: '历史不可覆盖' },
      { label: '共享消费者', value: '4 路', note: '下一版本保持一致' },
      { label: '回退点', value: 'V2', note: '仅读取旧版本，不覆盖' },
    ],
    evidenceGaps: ['规则 Gate Receipt 未形成。', '设备检验页尚未接入。'],
    nextActions: ['确认回流事件影响范围。', '等待新 Evidence 接受回执。', '生成并广播下一 Context Version。'],
    currentSituation: '四路回流已聚合为候选差异，下一版本尚未取得人工更新 Gate。',
    whyMe: '方遥负责版本反馈边界；模型只做候选影响分析，authority=none。',
    aiCompleted: ['已生成候选版本差异。', '已汇总候选四板块影响范围。'],
    primaryHumanAction: { action: '确认版本差异、影响范围和回退点。', owner: '智能更新·方遥', evidenceGap: '规则 Gate Receipt 与设备检验页。', humanGate: '智能更新 Gate' },
    nextHandoff: { target: 'credit-parse', receiver: '模型解析·顾青', contextPacket: ['新 Context Version', 'Evidence Event ID', '版本差异', '影响范围', '更新 Gate Receipt'] },
    successReceiptCondition: '方遥提交后 Receipt 记录新 Context Version、影响范围、回退点与四路广播状态。',
  },
} satisfies Record<string, FlowWorkspace>;
