const candidateFlows = Object.freeze({
  policy: Object.freeze([
    Object.freeze({
      id: "policy-precheck",
      label: "前置核验",
      summary: "已关联合成商机，并确认现场尽调材料仅用于界面演示。",
      status: "已完成",
      owner: "王晓",
      agent: "政策核验助手",
      evidenceCount: 12,
      updatedAt: "2026-08-28T09:20:00+08:00",
      exception: null,
      receipt: "RC-POLICY-001",
    }),
    Object.freeze({
      id: "policy-source",
      label: "原文依据",
      summary: "政策原文已建立索引，引用范围保持可追溯。",
      status: "已完成",
      owner: "李芳",
      agent: "政策核验助手",
      evidenceCount: 8,
      updatedAt: "2026-08-28T09:25:00+08:00",
      exception: null,
      receipt: "RC-POLICY-002",
    }),
    Object.freeze({
      id: "policy-scope",
      label: "适用范围",
      summary: "适用条件与限制已按当前演示数据整理。",
      status: "已完成",
      owner: "李芳",
      agent: "政策核验助手",
      evidenceCount: 6,
      updatedAt: "2026-08-28T09:30:00+08:00",
      exception: null,
      receipt: "RC-POLICY-003",
    }),
    Object.freeze({
      id: "policy-version",
      label: "规则版本",
      summary: "规则版本与生效时间已标记。",
      status: "进行中",
      owner: "周然",
      agent: "政策核验助手",
      evidenceCount: 4,
      updatedAt: "2026-08-28T09:35:00+08:00",
      exception: null,
      receipt: "RC-POLICY-004",
    }),
    Object.freeze({
      id: "policy-release",
      label: "人工发布",
      summary: "等待人工确认后发布结果。",
      status: "待处理",
      owner: "周然",
      agent: "人工操作台",
      evidenceCount: 2,
      updatedAt: "2026-08-28T09:40:00+08:00",
      exception: null,
      receipt: "RC-POLICY-005",
    }),
  ]),
  credit: Object.freeze([
    Object.freeze({
      id: "credit-parse",
      label: "多模态解析",
      summary: "演示材料已完成结构与要点解析。",
      status: "已完成",
      owner: "沈璐",
      agent: "信审解析助手",
      evidenceCount: 15,
      updatedAt: "2026-08-28T10:05:00+08:00",
      exception: null,
      receipt: "RC-CREDIT-001",
    }),
    Object.freeze({
      id: "credit-fact",
      label: "事实核验",
      summary: "关键事实已与合成证据对齐。",
      status: "已完成",
      owner: "沈璐",
      agent: "信审核验助手",
      evidenceCount: 11,
      updatedAt: "2026-08-28T10:10:00+08:00",
      exception: null,
      receipt: "RC-CREDIT-002",
    }),
    Object.freeze({
      id: "credit-onsite",
      label: "现场尽调",
      summary: "现场安排与反馈记录保持独立留痕。",
      status: "进行中",
      owner: "赵青",
      agent: "信审核验助手",
      evidenceCount: 7,
      updatedAt: "2026-08-28T10:15:00+08:00",
      exception: null,
      receipt: "RC-CREDIT-003",
    }),
    Object.freeze({
      id: "credit-evidence",
      label: "证据回链",
      summary: "结论与来源编号已建立回链。",
      status: "进行中",
      owner: "赵青",
      agent: "信审解析助手",
      evidenceCount: 9,
      updatedAt: "2026-08-28T10:20:00+08:00",
      exception: null,
      receipt: "RC-CREDIT-004",
    }),
    Object.freeze({
      id: "credit-judgment",
      label: "人工判断",
      summary: "等待授权人员完成复核判断。",
      status: "待处理",
      owner: "陆铭",
      agent: "人工操作台",
      evidenceCount: 3,
      updatedAt: "2026-08-28T10:25:00+08:00",
      exception: null,
      receipt: "RC-CREDIT-005",
    }),
  ]),
  commerce: Object.freeze([
    Object.freeze({
      id: "commerce-terms",
      label: "审批条件",
      summary: "审批条件清单已完成演示数据填充。",
      status: "已完成",
      owner: "韩雪",
      agent: "商务条件助手",
      evidenceCount: 10,
      updatedAt: "2026-08-28T11:00:00+08:00",
      exception: null,
      receipt: "RC-COMMERCE-001",
    }),
    Object.freeze({
      id: "commerce-contract",
      label: "合同任务",
      summary: "合同任务责任人与期限已标记。",
      status: "进行中",
      owner: "韩雪",
      agent: "商务任务助手",
      evidenceCount: 6,
      updatedAt: "2026-08-28T11:05:00+08:00",
      exception: null,
      receipt: "RC-COMMERCE-002",
    }),
    Object.freeze({
      id: "commerce-payment",
      label: "付款核验",
      summary: "付款前提与凭证状态已完成核对。",
      status: "进行中",
      owner: "宋清",
      agent: "商务核验助手",
      evidenceCount: 8,
      updatedAt: "2026-08-28T11:10:00+08:00",
      exception: null,
      receipt: "RC-COMMERCE-003",
    }),
    Object.freeze({
      id: "commerce-delivery",
      label: "交付查勘",
      summary: "交付状态查勘记录待补充确认。",
      status: "待处理",
      owner: "宋清",
      agent: "商务任务助手",
      evidenceCount: 4,
      updatedAt: "2026-08-28T11:15:00+08:00",
      exception: null,
      receipt: "RC-COMMERCE-004",
    }),
    Object.freeze({
      id: "commerce-acceptance",
      label: "人工验收",
      summary: "验收确认需由授权人员执行。",
      status: "待处理",
      owner: "陈昊",
      agent: "人工操作台",
      evidenceCount: 2,
      updatedAt: "2026-08-28T11:20:00+08:00",
      exception: null,
      receipt: "RC-COMMERCE-005",
    }),
  ]),
  asset: Object.freeze([
    Object.freeze({
      id: "asset-performance",
      label: "投放表现",
      summary: "投放表现指标基于合成数据展示。",
      status: "已完成",
      owner: "方蕾",
      agent: "资产监测助手",
      evidenceCount: 13,
      updatedAt: "2026-08-28T14:00:00+08:00",
      exception: null,
      receipt: "RC-ASSET-001",
    }),
    Object.freeze({
      id: "asset-signal",
      label: "异常信号",
      summary: "演示信号已标记为需关注。",
      status: "需关注",
      owner: "方蕾",
      agent: "资产监测助手",
      evidenceCount: 5,
      updatedAt: "2026-08-28T14:05:00+08:00",
      exception: "存在一条待复核的演示信号。",
      receipt: "RC-ASSET-002",
    }),
    Object.freeze({
      id: "asset-condition",
      label: "条件验证",
      summary: "相关条件的满足状态正在跟踪。",
      status: "进行中",
      owner: "孙启",
      agent: "资产核验助手",
      evidenceCount: 6,
      updatedAt: "2026-08-28T14:10:00+08:00",
      exception: null,
      receipt: "RC-ASSET-003",
    }),
    Object.freeze({
      id: "asset-bypass",
      label: "旁路评估",
      summary: "替代处理路径的适用性待评估。",
      status: "待处理",
      owner: "孙启",
      agent: "资产评估助手",
      evidenceCount: 3,
      updatedAt: "2026-08-28T14:15:00+08:00",
      exception: null,
      receipt: "RC-ASSET-004",
    }),
    Object.freeze({
      id: "asset-feedback",
      label: "结果反馈",
      summary: "处理结果将在确认后同步展示。",
      status: "待处理",
      owner: "何静",
      agent: "人工操作台",
      evidenceCount: 1,
      updatedAt: "2026-08-28T14:20:00+08:00",
      exception: null,
      receipt: "RC-ASSET-005",
    }),
  ]),
});

const stageDefinitions = Object.freeze([
  Object.freeze({ id: "policy", label: "政策" }),
  Object.freeze({ id: "credit", label: "信审" }),
  Object.freeze({ id: "commerce", label: "商务" }),
  Object.freeze({ id: "asset", label: "资产" }),
]);

export const financingLeasingProjection = Object.freeze({
  caseId: "FL-DEMO-001",
  stages: Object.freeze(stageDefinitions.map((stage) => Object.freeze({
    id: stage.id,
    label: stage.label,
    slots: Object.freeze(candidateFlows[stage.id]),
  }))),
});
