const steps = [
  { id:'submit', lane:'Business', title:'Direct submit', sub:'material enters review', role:'business', action:'submit', command:'submitForRiskReview (simulated)', state:'ReviewRound 1 begins; material is submitted.', policy:'Business has submit capability, never pass or veto.', event:'RiskReviewSubmitted', test:'Accepted only as a local simulated command.' },
  { id:'s1', lane:'System', title:'ContextSnapshot S1', sub:'immutable baseline', role:'business', action:'snapshot1', command:'submitForRiskReview (same simulated transaction)', state:'Snapshot S1 is immutable; it records the submitted text.', policy:'A later snapshot cannot overwrite S1.', event:'ContextSnapshotCreated', test:'S1 remains visible after S2 appears.' },
  { id:'a1', lane:'Intelligence', title:'Advisory A1', sub:'provider-generated · unverified', role:'agent', action:'advisory1', command:'invokeDeterministicAdvisory (local simulated)', state:'A1 is advisoryOnly with separate model confidence.', policy:'Agent output cannot create a Decision or control outcome.', event:'AdvisoryArtifactCreated', test:'Clearly marked simulated and unverified.' },
  { id:'communicate', lane:'Risk control', title:'Communicate', sub:'request missing evidence', role:'risk', action:'communicate', command:'communicateRiskChallenge (simulated)', state:'ReviewRound 1 becomes needs_input; communication is non-terminal.', policy:'Risk may communicate a Challenge without approving or rejecting.', event:'RiskChallengeCommunicated', test:'No pass/veto Decision is created.' },
  { id:'challenge', lane:'System', title:'Challenge.open', sub:'date evidence missing', role:'risk', action:'challenge', command:'communicateRiskChallenge (same simulated transition)', state:'Mandatory Challenge is open; policy guidance is needs_input.', policy:'An open mandatory Challenge prevents Decision readiness.', event:'RiskChallengeCommunicated', test:'Risk Decision is rejected while it remains open.' },
  { id:'supplement', lane:'Business', title:'Supplement evidence', sub:'new dated source', role:'business', action:'supplement', command:'answerChallenge (simulated)', state:'The same ReviewRound answers the Challenge with supplemental material and creates a new ContextSnapshot.', policy:'Business may answer, but cannot resolve a Challenge.', event:'RiskChallengeAnswered', test:'This does not overwrite S1.' },
  { id:'s2', lane:'System', title:'ContextSnapshot S2', sub:'new immutable revision', role:'business', action:'snapshot2', command:'answerChallenge (same simulated transaction)', state:'S2 includes supplemental material and preserves S1.', policy:'Immutable history; S1 is preserved.', event:'ContextSnapshotCreated', test:'S1/S2 comparison shows different material.' },
  { id:'a2', lane:'Intelligence', title:'Advisory A2', sub:'provider-generated · unverified', role:'agent', action:'advisory2', command:'invokeDeterministicAdvisory (local simulated)', state:'A2 is advisoryOnly and responds to the new context.', policy:'Agent cannot pass, veto, or create a Decision.', event:'AdvisoryArtifactCreated', test:'Agent pass/veto attempt is rejected.' },
  { id:'resolve', lane:'Risk control', title:'Challenge.resolved', sub:'risk completes review', role:'risk', action:'resolve', command:'resolveRiskChallenge (simulated)', state:'Risk resolves the Challenge; ReviewRound returns to under_review.', policy:'Only Risk may resolve or reopen a Challenge.', event:'RiskChallengeResolved', test:'Decision remains unavailable until this transition.' },
  { id:'decision', lane:'Risk control', title:'Risk pass / veto', sub:'sole final authority', role:'risk', action:'decision', command:'recordRiskDecision (simulated only)', state:'The lab reports a hypothetical pass/veto result; no real Decision record exists.', policy:'Only Risk with decide capability can select pass or veto.', event:'RiskDecisionRecorded', test:'Business and agent attempts are rejected with no event.' },
];
const lanes = ['Business','System','Intelligence','Risk control'];
const state = { completed:[], round:0, challenge:'none', snapshots:[], decision:'None — this lab never creates authoritative Decisions.', events:[], outcome:'Awaiting synthetic action.' };
const $ = selector => document.querySelector(selector);
const workflow = $('#workflow'); const role = $('#role'); const action = $('#action');
function actionOptions(){ const available = steps.filter(s => s.role === role.value && !state.completed.includes(s.id)); const forbidden = role.value === 'risk' ? '' : '<option value="pass">Attempt pass / veto (must reject)</option>'; action.innerHTML = available.map(s => `<option value="${s.action}">${s.title}</option>`).join('') + forbidden || '<option value="pass">Attempt pass / veto</option>'; }
function renderWorkflow(){ workflow.innerHTML = lanes.map(lane => `<div class="lane"><div class="lane-label">${lane}</div><div class="lane-track">${steps.filter(s=>s.lane===lane).map(s=>`<button class="node ${state.completed.includes(s.id)?'done':''}" data-id="${s.id}">${s.title}<small>${s.sub}</small></button>`).join('')}</div></div>`).join(''); workflow.querySelectorAll('.node').forEach(node => node.addEventListener('click', () => showDetails(steps.find(s=>s.id===node.dataset.id)))); }
function showDetails(step){ $('#detail-title').textContent = step.title; $('#detail-status').textContent = state.completed.includes(step.id) ? 'SIMULATED EVENT RECORDED' : 'NOT YET EXECUTED'; $('#details').className='details'; $('#details').innerHTML = [['Command',step.command],['State',step.state],['Policy',step.policy],['Event',step.event],['Test',step.test]].map(([key,value])=>`<section class="dimension"><h3>${key}</h3><p>${value}</p></section>`).join(''); document.querySelectorAll('.node').forEach(n=>n.classList.toggle('selected', n.dataset.id===step.id)); }
function addEvent(step){ state.events.unshift({ type:step.event, time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}), actor:step.lane, note:step.title }); }
function complete(step){ state.completed.push(step.id); if(step.id==='submit') state.round=1; if(step.id==='challenge') state.challenge='open · mandatory evidence date'; if(step.id==='s1'||step.id==='s2') state.snapshots.push({ id:step.id.toUpperCase(), text:$('#material').value.trim() || 'No synthetic material entered.' }); if(step.id==='resolve') state.challenge='resolved by Risk (simulated)'; addEvent(step); state.outcome=`Allowed: ${step.title}. This is a local, simulated event only.`; render(); showDetails(step); }
function reject(message){ state.outcome=`Rejected: ${message} No simulated event was added.`; $('#outcome').className='outcome rejected'; $('#outcome').textContent=state.outcome; }
function canComplete(step){ const i=steps.indexOf(step); return !state.completed.includes(step.id) && steps.slice(0,i).every(s=>state.completed.includes(s.id)); }
function render(){ renderWorkflow(); actionOptions(); $('#step-counter').textContent=`${state.completed.length} / ${steps.length} completed`; $('#outcome').className='outcome accepted'; $('#outcome').textContent=state.outcome; $('#state-summary').innerHTML=[['Adapter','Local simulated · backend disconnected'],['ReviewRound',state.round || 'not started'],['Challenge',state.challenge],['Latest Snapshot',state.snapshots.at(-1)?.id || 'none'],['Decision',state.decision],['Agent rule','advisoryOnly · unverified']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join(''); $('#timeline').innerHTML=state.events.length?state.events.map(e=>`<li><time>${e.time} · ${e.actor}</time>${e.type}: ${e.note}</li>`).join(''):'<li><time>NO EVENTS</time>Rejected commands will not appear here.</li>'; $('#snapshots').innerHTML=state.snapshots.length?state.snapshots.map((s,i)=>`<section class="snapshot ${i===state.snapshots.length-1?'current':''}"><span class="tag">IMMUTABLE · SIMULATED</span><h3>${s.id}</h3><p>${escapeHtml(s.text)}</p></section>`).join(''):'<p class="microcopy">S1 and S2 will be shown side-by-side as separate immutable simulated records.</p>'; }
function escapeHtml(value){ const d=document.createElement('div'); d.textContent=value; return d.innerHTML; }
role.addEventListener('change', actionOptions);
$('#command-form').addEventListener('submit', event => { event.preventDefault(); const selected=action.value; const step=steps.find(s=>s.role===role.value&&s.action===selected); if(['pass','veto'].includes(selected) || (role.value!=='risk' && selected==='resolve')) return reject('Only the Risk human can pass or veto.'); if(role.value==='agent' && !step) return reject('Project agent is advisoryOnly and cannot control the gate.'); if(!step) return reject('That action is unavailable in the frozen workflow topology.'); if(!canComplete(step)) return reject('The sequence is fixed. Complete the earlier workflow event first.'); if(step.id==='decision' && state.challenge!=='resolved by Risk (simulated)') return reject('Challenge resolution is required before a Risk Decision.'); complete(step); });
render();
