import { mkdtempSync, readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

process.env.V5_PREVIEW_DATA_DIR = mkdtempSync(join(tmpdir(), 'jw-independent-remote-review-'));
const svc = await import('../../jianwei-v3/site/lib/v5-preview/remote-service.ts');
let serial = 0;
const write = (fn, body) => fn({requestId: `independent-${++serial}`, expectedVersion: svc.getRemoteState().remoteVersion, ...body});
const sessionId = write(svc.createRemoteSession, {title:'Independent synthetic review'}).session.sessionId;
const evidence = write(svc.attachEvidence, {sessionId, fixtureId:'fixture-inspection'}).evidence;
const review = (action, targetId=evidence.evidenceId) => write(svc.createReview, {sessionId,targetType:'evidence',targetId,targetVersion:1,action,opinion:'Synthetic independent check'});
const findings = [];
review('confirm');
review('request_retake');
let detail = svc.getRemoteSessionDetail(sessionId);
findings.push({check:'confirmed_then_retake',actual:detail.evidence[0].verificationStatus, expected:'confirmation suspended pending retake'});
assert.equal(detail.evidence[0].verificationStatus,'human_verified');
review('pause_round');
const annotation = write(svc.createAnnotation,{sessionId,evidenceId:evidence.evidenceId,evidenceVersion:1,question:'Synthetic pause test',rect:{x:0.1,y:0.1,w:0.2,h:0.2}}).annotation;
const simulated = write(svc.simulateFollowUps,{sessionId,annotationId:annotation.annotationId});
findings.push({check:'paused_model_step',sessionStatus:svc.getRemoteSessionDetail(sessionId).session.status,simulated:simulated.simulated,expected:'judgment/model execution blocked while paused'});
assert.equal(simulated.simulated,true);
write(svc.supersedeEvidence,{sessionId,evidenceId:evidence.evidenceId,fixtureId:'fixture-equipment'});
const staleReview = review('confirm');
findings.push({check:'confirm_superseded_evidence',accepted:staleReview.ok,expired:svc.getRemoteSessionDetail(sessionId).evidence[0].expired,expected:'reject new confirmation of superseded evidence'});
assert.equal(staleReview.ok,true);
const actualHash = createHash('sha256').update(svc.renderFixtureSvg('fixture-inspection')).digest('hex');
findings.push({check:'original_image_digest',matchesServedBytes:evidence.sha256===actualHash,expected:true});
assert.notEqual(evidence.sha256,actualHash);
const labels=['方案金额','期限','租金现金流合计（测试口径）','资金成本（测试口径）','预期信用损失（测试口径）','运营及核验成本（测试口径）'];
const inputs = labels.map((label,i)=>({label,value:[100,12,200,10,10,10][i],unit:i===1?'月':'万元',source:'test_fixture'}));
const calculationRequest={requestId:'calculation-replay',expectedVersion:svc.getRemoteState().remoteVersion,sessionId,mode:'contract_fixture',inputs};
const first=svc.attemptCalculation(calculationRequest);
const changed=structuredClone(calculationRequest);
changed.inputs[2].value=1;
const second=svc.attemptCalculation(changed);
findings.push({check:'calculation_changed_payload_same_id',sameResult:first.calculation.calcId===second.calculation.calcId,firstStatus:first.calculation.status,secondStatus:second.calculation.status,expected:'REQUEST_MISMATCH'});
assert.equal(first.calculation.calcId,second.calculation.calcId);
const ts = (await import('../../jianwei-v3/site/node_modules/typescript/lib/typescript.js')).default;
const pageSource = readFileSync(new URL('../../jianwei-v3/site/app/v5-preview/remote-session/page.tsx',import.meta.url),'utf8');
const ast = ts.createSourceFile('page.tsx',pageSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
let initializer;
function visit(node) {
  if(ts.isVariableDeclaration(node) && node.name.getText(ast)==='runWrite') initializer=node.initializer.getText(ast);
  ts.forEachChild(node,visit);
}
visit(ast);
assert.ok(initializer);
const sent=[];
const attemptRef={current:null};
const noop=()=>{};
const context={useCallback:fn=>fn,setBusy:noop,setNotice:noop,setAttemptPending:noop,setRemoteVersion:noop,attemptRef,session:null,loadDetail:async()=>{},loadState:async()=>{},newRequestId:()=>`fe-${sent.length+1}`,userFacing:()=>'',postRemote:async(path,body,requestId)=>{sent.push({path,body,requestId});throw Object.assign(new Error('synthetic response loss'),{code:'NETWORK'});}};
const compiled=ts.transpileModule(`const extracted=${initializer}; extracted;`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const runWrite=runInNewContext(compiled,context);
await runWrite('evidence',{fixtureId:'fixture-inspection',expectedVersion:1},false,noop,'synthetic-session');
await runWrite('evidence',{fixtureId:'fixture-inspection',expectedVersion:1},false,noop,'synthetic-session');
findings.push({check:'frontend_repeat_after_network_unknown',ids:sent.map(s=>s.requestId),sameId:sent[0].requestId===sent[1].requestId,expected:'same frozen request id/body'});
assert.notEqual(sent[0].requestId,sent[1].requestId);
console.log(JSON.stringify({dataDirectory:process.env.V5_PREVIEW_DATA_DIR,findings},null,2));
