import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { DurableApp, ActorClass } from '../src/index.mjs'
import { canonicalHash } from '../src/event-log.mjs'
const business={id:'business',class:ActorClass.HUMAN}; const env=(cap,key,v,p)=>({actor:business,capability:cap,idempotencyKey:key,expectedVersion:v,requestHash:canonicalHash(p)}); const path=async()=>join(await mkdtemp(join(tmpdir(),'tag-model-')),'x.sqlite')
const deferred=()=>{let resolve,reject;return {promise:new Promise((a,b)=>{resolve=a;reject=b}),resolve,reject}}
function boot(app){const p={id:'p',title:'p',memberships:[{principalId:'business',capabilities:['addEvidence','precheck','submit','invoke','message']} ]};return app.bootstrapProject(p,env(undefined,'b',undefined,p))}
function prepared(app){const t=boot(app).thread;const e={threadId:t.id,title:'id',locator:'p:1',content:'PRIVATE-EVIDENCE',criterionCode:'identity'};app.command('p','addEvidence',e,env('addEvidence','e',1,e));const s={threadId:t.id};const r=app.command('p','submitForRiskReview',s,env('submit','s',2,s));const p={threadId:t.id,reviewRoundId:r.reviewRound.id,snapshotId:r.snapshot.id,provider:'glm53',promptVersion:'evidence_first_v1',reasoningEffort:'low',citations:r.snapshot.evidence,agentId:'a'};return {r,p}}
const draft=id=>({modelConfidence:.5,judgmentClaims:[{criterionCode:'identity',position:'support',rationale:'x',citationEvidenceIds:[id]}],evidenceGaps:[{criterionCode:'business_reality'}],nextBestEvidence:{criterionCode:'business_reality'}})

test('same-key deferred requests have one owner and no public secret leakage',async()=>{const d=deferred();let calls=0;const app=new DurableApp(await path(),{modelAdapter:{analyze:async()=>{calls++;return d.promise}},tokenFactory:()=> 'RAW-OWNER-TOKEN'});const {r,p}=prepared(app);const a=app.command('p','requestModelAdvisory',p,env('invoke','k',r.threadVersion,p));const b=await app.command('p','requestModelAdvisory',p,env('invoke','k',r.threadVersion,p));assert.equal(calls,1);assert.equal(b.advisoryRun.status,'running');d.resolve({draft:draft(p.citations[0].evidenceId),requestId:'x',usage:null,elapsedMs:1});await a;const text=JSON.stringify(app.state('p'))+JSON.stringify(app.events('p'));assert.equal(text.includes('RAW-OWNER-TOKEN'),false);assert.equal(text.includes('PRIVATE-EVIDENCE'),false);app.close()})

test('provider failures become terminal failed runs without artifacts',async()=>{for(const code of ['ADVISORY_UNAVAILABLE','ADVISORY_RATE_LIMITED','ADVISORY_INVALID_OUTPUT']){const app=new DurableApp(await path(),{modelAdapter:{analyze:async()=>{const e=new Error(code);e.code=code;throw e}}});const {r,p}=prepared(app);const out=await app.command('p','requestModelAdvisory',p,env('invoke',code,r.threadVersion,p));assert.equal(out.advisoryRun.status,'failed');assert.equal(out.advisoryRun.failureCode,code);assert.equal(app.state('p').artifacts.length,0);app.close()}})

test('two DurableApp instances share one valid-lease deferred run',async()=>{const file=await path(),d=deferred();let calls=0;const adapter={analyze:async()=>{calls++;return d.promise}};const one=new DurableApp(file,{modelAdapter:adapter}),{r,p}=prepared(one);const pending=one.command('p','requestModelAdvisory',p,env('invoke','shared',r.threadVersion,p));const two=new DurableApp(file,{modelAdapter:adapter});const second=await two.command('p','requestModelAdvisory',p,env('invoke','shared',r.threadVersion,p));assert.equal(calls,1);assert.equal(second.advisoryRun.status,'running');assert.equal(second.advisoryRun.id,one.state('p').advisoryRuns[0].id);assert.equal(two.events('p').filter(x=>x.type==='AdvisoryRunRequested').length,1);d.resolve({draft:draft(p.citations[0].evidenceId),requestId:'x',usage:null,elapsedMs:1});await pending;one.close();two.close()})

test('expired lease takeover fences old resolve and old reject while new owner succeeds',async()=>{for(const mode of ['resolve','reject']){let tick=0,serial=0,calls=0;const old=deferred(),fresh=deferred(),file=await path();const adapter={analyze:async()=>{calls++;return calls===1?old.promise:fresh.promise}};const options={modelAdapter:adapter,leaseMs:10,clock:()=>tick,tokenFactory:()=>`token-${++serial}`};const one=new DurableApp(file,options),{r,p}=prepared(one);const first=one.command('p','requestModelAdvisory',p,env('invoke',`take-${mode}`,r.threadVersion,p));tick=20;const two=new DurableApp(file,options);const second=two.command('p','requestModelAdvisory',p,env('invoke',`take-${mode}`,r.threadVersion,p));await Promise.resolve();assert.equal(calls,2);const run=two.state('p').advisoryRuns[0];assert.equal(run.attempt,2);assert.equal(run.fencingToken,2);if(mode==='resolve')old.resolve({draft:draft(p.citations[0].evidenceId),requestId:'old',usage:null,elapsedMs:1});else old.reject(Object.assign(new Error('old'),{code:'ADVISORY_UNAVAILABLE'}));await assert.rejects(first,/ADVISORY_RUN_FENCE_CONFLICT/);fresh.resolve({draft:draft(p.citations[0].evidenceId),requestId:'new',usage:null,elapsedMs:1});await second;assert.equal(two.state('p').artifacts.length,1);assert.equal(two.state('p').advisoryRuns[0].status,'succeeded');one.close();two.close()}})

test('version competition fails the run durably and stale takeover does not call a model',async()=>{let tick=0,calls=0;const d=deferred(),file=await path(),options={leaseMs:10,clock:()=>tick,modelAdapter:{analyze:async()=>{calls++;return d.promise}}};let app=new DurableApp(file,options),{r,p}=prepared(app);const pending=app.command('p','requestModelAdvisory',p,env('invoke','version',r.threadVersion,p));const message={threadId:p.threadId,content:'human change',replyToMessageId:null,citations:[]};app.command('p','appendHumanMessage',message,env('message','m',r.threadVersion+1,message));d.resolve({draft:draft(p.citations[0].evidenceId),requestId:'x',usage:null,elapsedMs:1});const failed=await pending;assert.equal(failed.advisoryRun.failureCode,'VERSION_CONFLICT');assert.equal(app.state('p').artifacts.length,0);app.close();app=new DurableApp(file,options);assert.equal(app.state('p').advisoryRuns[0].status,'failed');const replay=await app.command('p','requestModelAdvisory',p,env('invoke','version',r.threadVersion,p));assert.equal(calls,1);assert.equal(replay.advisoryRun.status,'failed');app.close()})

test('SQL and public projections redact owner token and Evidence content across terminal replay',async()=>{const file=await path();let calls=0;const app=new DurableApp(file,{tokenFactory:()=> 'RAW-OWNER-TOKEN',modelAdapter:{analyze:async({citations})=>{calls++;return {draft:draft(citations[0].evidenceId),requestId:'x',usage:null,elapsedMs:1}}}}),{r,p}=prepared(app);const out=await app.command('p','requestModelAdvisory',p,env('invoke','privacy',r.threadVersion,p));const events=app.events('p').length;const replay=await app.command('p','requestModelAdvisory',p,env('invoke','privacy',r.threadVersion,p));assert.equal(calls,1);assert.equal(replay.advisoryRun.id,out.advisoryRun.id);assert.equal(app.events('p').length,events);const db=new DatabaseSync(file);const control=db.prepare('SELECT owner_token_hash FROM advisory_run_control').get();const rows=db.prepare('SELECT payload,envelope,result FROM commands WHERE command != ?').all('addEvidence');const text=JSON.stringify(rows)+JSON.stringify(app.state('p'))+JSON.stringify(app.events('p'))+JSON.stringify(db.prepare('SELECT body FROM outbox').all());assert.notEqual(control.owner_token_hash,'RAW-OWNER-TOKEN');assert.equal(text.includes('RAW-OWNER-TOKEN'),false);assert.equal(text.includes('PRIVATE-EVIDENCE'),false);db.close();app.close()})

test('stale lease takeover after a human mutation fails without a second model call',async()=>{let tick=0,calls=0;const d=deferred(),file=await path(),options={leaseMs:10,clock:()=>tick,modelAdapter:{analyze:async()=>{calls++;return d.promise}}};const one=new DurableApp(file,options),{r,p}=prepared(one);const old=one.command('p','requestModelAdvisory',p,env('invoke','stale-take',r.threadVersion,p));const m={threadId:p.threadId,content:'change',replyToMessageId:null,citations:[]};const two=new DurableApp(file,options);two.command('p','appendHumanMessage',m,env('message','change',r.threadVersion+1,m));tick=20;const result=await two.command('p','requestModelAdvisory',p,env('invoke','stale-take',r.threadVersion,p));assert.equal(calls,1);assert.equal(result.advisoryRun.status,'failed');assert.equal(result.advisoryRun.failureCode,'VERSION_CONFLICT');assert.equal(result.advisoryRun.attempt,2);assert.equal(result.advisoryRun.fencingToken,2);assert.equal(two.state('p').artifacts.length,0);assert.equal(two.state('p').decisions.length,0);d.resolve({draft:draft(p.citations[0].evidenceId),requestId:'old',usage:null,elapsedMs:1});await assert.rejects(old,/ADVISORY_RUN_FENCE_CONFLICT/);assert.equal(two.state('p').advisoryRuns[0].status,'failed');one.close();two.close();const restored=new DurableApp(file,options);assert.equal(restored.state('p').advisoryRuns[0].status,'failed');restored.close()})

test('judgment without a model never recommends deterministic or model commands',async()=>{const app=new DurableApp(await path()),{r,p}=prepared(app);const pre=app.judgment('p',p.threadId);assert.equal(pre.modelEvaluation.status,'not_connected');assert.notEqual(pre.nextAction.command,'invokeDeterministicAdvisory');assert.notEqual(pre.nextAction.command,'requestModelAdvisory');assert.equal(pre.nextAction.code,'RISK_DECISION');app.close()})

test('connected running judgment waits without an executable command',async()=>{const d=deferred(),app=new DurableApp(await path(),{modelAdapter:{analyze:async()=>d.promise}}),{r,p}=prepared(app);const pending=app.command('p','requestModelAdvisory',p,env('invoke','wait',r.threadVersion,p));await Promise.resolve();const j=app.judgment('p',p.threadId);assert.equal(j.nextAction.code,'WAIT_ADVISORY');assert.equal(j.nextAction.command,undefined);d.resolve({draft:draft(p.citations[0].evidenceId),requestId:'SECRET-REQUEST',usage:null,elapsedMs:1});await pending;const done=app.judgment('p',p.threadId);assert.equal(done.modelEvaluation.status,'succeeded');assert.equal(done.modelEvaluation.requestIdPresent,true);assert.equal(JSON.stringify(done).includes('SECRET-REQUEST'),false);app.close()})

test('failed connected formal review follows human decision rather than deterministic advisory',async()=>{const app=new DurableApp(await path(),{modelAdapter:{analyze:async()=>{const e=new Error('x');e.code='ADVISORY_UNAVAILABLE';throw e}}}),{r,p}=prepared(app);await app.command('p','requestModelAdvisory',p,env('invoke','failed-judge',r.threadVersion,p));const j=app.judgment('p',p.threadId);assert.equal(j.modelEvaluation.status,'failed');assert.equal(j.nextAction.code,'RISK_DECISION');assert.notEqual(j.nextAction.command,'invokeDeterministicAdvisory');app.close()})

test('real precheck requests GLM then follows missing evidence or ready submission',async()=>{const app=new DurableApp(await path(),{modelAdapter:{analyze:async({citations})=>({draft:draft(citations[0].evidenceId),requestId:'x',usage:null,elapsedMs:1})}});const t=boot(app).thread;const e={threadId:t.id,title:'id',locator:'p',content:'id',criterionCode:'identity'};app.command('p','addEvidence',e,env('addEvidence','pre-e',1,e));const a={threadId:t.id};const pre=app.command('p','createPrecheckAttempt',a,env('precheck','pre',2,a));const payload={threadId:t.id,snapshotId:pre.snapshot.id,precheckAttemptId:pre.precheckAttempt.id,provider:'glm53',promptVersion:'evidence_first_v1',reasoningEffort:'low',citations:pre.snapshot.evidence,agentId:'a'};assert.equal(app.judgment('p',t.id).nextAction.command,'requestModelAdvisory');await app.command('p','requestModelAdvisory',payload,env('invoke','pre-model',pre.threadVersion,payload));assert.equal(app.judgment('p',t.id).nextAction.code,'ADD_EVIDENCE');app.close()})

test('formal success binds review packet artifact, scoped citations and human authority',async()=>{const app=new DurableApp(await path(),{modelAdapter:{analyze:async({citations})=>({draft:draft(citations[0].evidenceId),requestId:'x',usage:null,elapsedMs:1})}}),{r,p}=prepared(app);await app.command('p','requestModelAdvisory',p,env('invoke','formal-model',r.threadVersion,p));const j=app.judgment('p',p.threadId);assert.equal(j.reviewPacket.latestArtifact.id,j.modelEvaluation.artifactId);assert.equal(j.reviewPacket.citations[0].evidenceId,p.citations[0].evidenceId);assert.equal(j.disagreements.find(x=>x.criterionCode==='identity').modelPosition,'support');assert.equal(j.disagreements.find(x=>x.criterionCode==='business_reality').modelPosition,'unknown');assert.equal(j.reviewPacket.authorityStatement,'仅风险人类可通过／否决');app.close()})
